In [1]:
import numpy as np

import tensorflow as tf
from tensorflow import keras

In [2]:
class MLP(keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = keras.layers.Flatten()
        self.dense1 = keras.layers.Dense(256, activation='relu')
        self.dense2 = keras.layers.Dense(10)
        return 
    
    def call(self, inputs):
        x = self.flatten(inputs)
        x = self.dense1(x)
        output = self.dense2(x)
        return output


In [3]:
X = tf.random.uniform((2, 20))
net = MLP()
net(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.1286947 ,  0.07764449,  0.35278645, -0.12542996, -0.11712442,
         0.19695786,  0.23840117,  0.13067661,  0.15444487, -0.14986958],
       [-0.10391721,  0.33540004,  0.25835368, -0.1754843 , -0.2553258 ,
         0.12316856,  0.12006948,  0.1947205 ,  0.20065379, -0.10116769]],
      dtype=float32)>

In [4]:
model = keras.Sequential([
    keras.layers.Flatten(),
    keras.layers.Dense(256, activation='relu'), 
    keras.layers.Dense(10),
])
model(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.06339863,  0.12825064, -0.08234776, -0.22646987, -0.18462273,
        -0.10175624, -0.23564984, -0.2492517 ,  0.05311234,  0.30320397],
       [ 0.05995935,  0.13287617,  0.21909091, -0.29701728, -0.12669116,
        -0.10869291, -0.47255224, -0.259065  , -0.17982903,  0.17746148]],
      dtype=float32)>

In [7]:
class FancyMLP(keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = keras.layers.Flatten()
        self.constant_weight = tf.constant(
            tf.random.uniform((20, 20))
        )
        self.dense = keras.layers.Dense(20, activation='relu')
        return 
    
    def call(self, inputs):
        x = self.flatten(inputs)
        x = tf.nn.relu(tf.matmul(x, self.constant_weight) + 1)
        x = self.dense(x)
        while tf.norm(x) > 1:
            x /= 2
        if tf.norm(x) < 0.8:
            x *= 10
        return tf.reduce_sum(x)
    

In [9]:
net = FancyMLP()
net(X)

<tf.Tensor: shape=(), dtype=float32, numpy=27.905592>

In [10]:
class NestMLP(keras.Model):
    def __init__(self):
        super().__init__()
        self.net = keras.Sequential([
            keras.layers.Flatten(),
            keras.layers.Dense(64, activation='relu'), 
            keras.layers.Dense(32, activation='relu'), 
        ])
        self.dense = keras.layers.Dense(16, activation='relu')
        return 
    
    def call(self, inputs):
        return self.dense(self.net(inputs))


net = keras.Sequential([
    NestMLP(), 
    keras.layers.Dense(20), 
    FancyMLP()
])
net(X)

<tf.Tensor: shape=(), dtype=float32, numpy=23.448265>