In [1]:
import tensorflow as tf
print(tf.__version__)

2.1.0


In [2]:
x = tf.constant(range(20))
x

In [10]:
X = tf.reshape(x, [4, 5])
X

In [15]:
tf.zeros([2, 3, 4]), tf.ones([3, 2, 4]), tf.random.normal([2, 3, 4], mean=0, stddev=1)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [18]:
X = tf.ones([3, 4])
Y = tf.random.normal([3, 4], mean=0, stddev=1)

In [21]:
X*Y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.3425169 ,  0.6518309 , -1.2926161 , -0.18768711],
       [ 1.1925871 ,  0.9597996 ,  1.7320682 , -0.20454542],
       [ 0.5878526 ,  0.11634899,  1.8846494 ,  0.61894566]],
      dtype=float32)>

In [24]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.1709893,  3.6799097,  3.2077966],
       [-1.1709893,  3.6799097,  3.2077966],
       [-1.1709893,  3.6799097,  3.2077966]], dtype=float32)>

In [63]:
tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 1.        ,  1.        ,  1.        ,  1.        ],
        [ 1.        ,  1.        ,  1.        ,  1.        ],
        [ 1.        ,  1.        ,  1.        ,  1.        ],
        [ 0.6574831 ,  1.6518309 , -0.29261613,  0.8123129 ],
        [ 2.1925871 ,  1.9597995 ,  2.732068  ,  0.79545456],
        [ 1.5878526 ,  1.116349  ,  2.8846493 ,  1.6189456 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 1.        ,  1.        ,  1.        ,  1.        ,  0.6574831 ,
          1.6518309 , -0.29261613,  0.8123129 ],
        [ 1.        ,  1.        ,  1.        ,  1.        ,  2.1925871 ,
          1.9597995 ,  2.732068  ,  0.79545456],
        [ 1.        ,  1.        ,  1.        ,  1.        ,  1.5878526 ,
          1.116349  ,  2.8846493 ,  1.6189456 ]], dtype=float32)>)

In [36]:
Z = tf.random.normal([2, 3, 4], mean=0, stddev=1)
tf.reduce_sum(Z), tf.reduce_sum(Z, axis=0), tf.reduce_sum(Z, axis=1), tf.reduce_sum(Z, axis=2), tf.reduce_sum(Z, axis=-1)

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 1.3810995e+00,  8.6480683e-01,  1.7167628e-03, -3.0366843e+00],
        [ 6.4027393e-01, -4.5167044e-02,  7.1011460e-01,  2.1080260e+00],
        [ 8.2770503e-01, -5.1045275e-01, -8.1291234e-01,  3.7466583e+00]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 0.49633884, -0.42442334,  2.0751474 ,  0.20979059],
        [ 2.3527396 ,  0.7336104 , -2.1762283 ,  2.6082096 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.92568564,  2.517031  ,  0.7655082 ],
        [ 0.13662446,  0.8962167 ,  2.4854903 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.92568564,  2.517031  ,  0.7655082 ],
        [ 0.13662446,  0.8962167 ,  2.4854903 ]], dtype=float32)>)

In [37]:
tf.norm(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=5.8631024>

In [42]:
A = tf.reshape(tf.constant(range(3)), [1, 3])
B = tf.reshape(tf.constant(range(4)), [4, 1])
A, B

(<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[0, 1, 2]])>,
 <tf.Tensor: shape=(4, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2],
        [3]])>)

In [43]:
A + B

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])>

In [44]:
Z

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 0.1384654 ,  1.4035888 , -0.41804293, -2.049697  ],
        [-0.55301964, -0.2845439 ,  2.0196917 ,  1.3349028 ],
        [ 0.9108931 , -1.5434682 ,  0.47349858,  0.92458475]],

       [[ 1.242634  , -0.53878194,  0.4197597 , -0.98698735],
        [ 1.1932936 ,  0.23937686, -1.3095771 ,  0.7731233 ],
        [-0.08318806,  1.0330155 , -1.2864109 ,  2.8220737 ]]],
      dtype=float32)>

In [45]:
Z[1]

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.242634  , -0.53878194,  0.4197597 , -0.98698735],
       [ 1.1932936 ,  0.23937686, -1.3095771 ,  0.7731233 ],
       [-0.08318806,  1.0330155 , -1.2864109 ,  2.8220737 ]],
      dtype=float32)>

In [51]:
Z[1,2,3]

<tf.Tensor: shape=(), dtype=float32, numpy=2.8220737>

In [49]:
Z1 = tf.Variable(Z)

In [52]:
Z1[1,2,3].assign(10)

<tf.Variable 'UnreadVariable' shape=(2, 3, 4) dtype=float32, numpy=
array([[[ 0.1384654 ,  1.4035888 , -0.41804293, -2.049697  ],
        [-0.55301964, -0.2845439 ,  2.0196917 ,  1.3349028 ],
        [ 0.9108931 , -1.5434682 ,  0.47349858,  0.92458475]],

       [[ 1.242634  , -0.53878194,  0.4197597 , -0.98698735],
        [ 1.1932936 ,  0.23937686, -1.3095771 ,  0.7731233 ],
        [-0.08318806,  1.0330155 , -1.2864109 , 10.        ]]],
      dtype=float32)>

In [53]:
Z1[1,2,3]

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [57]:
X = tf.Variable(X)
Y = tf.cast(Y, dtype=tf.float32)
X, Y

(<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.3425169 ,  0.6518309 , -1.2926161 , -0.18768711],
        [ 1.1925871 ,  0.9597996 ,  1.7320682 , -0.20454542],
        [ 0.5878526 ,  0.11634899,  1.8846494 ,  0.61894566]],
       dtype=float32)>)

In [58]:
before = id(Y)
Y = X + Y
after = id(Y)
print(before == after)

False


In [59]:
import numpy as np

In [60]:
P = np.ones([2, 3])
D = tf.constant(P)

In [61]:
P, D

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 <tf.Tensor: shape=(2, 3), dtype=float64, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]])>)

In [62]:
np.array(D)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
x = tf.random.normal([4, 1], mean=0, stddev=1)
x

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 0.5467824 ],
       [-0.94656646],
       [ 0.68916947],
       [ 0.80746514]], dtype=float32)>

In [72]:
# 2x^2 ==> 4x
with tf.GradientTape() as t:
    t.watch(x)
    y = 2 * tf.matmul(tf.transpose(x), x)
dy_dx = t.gradient(y, x)
dy_dx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 2.1871295],
       [-3.7862659],
       [ 2.7566779],
       [ 3.2298605]], dtype=float32)>

In [73]:
4*x

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 2.1871295],
       [-3.7862659],
       [ 2.7566779],
       [ 3.2298605]], dtype=float32)>

In [75]:
with tf.GradientTape(persistent=True) as g:
    g.watch(x)
    y = x * x
    z = y * y
    dz_dx = g.gradient(z, x)  # 4*x^3
    dy_dx = g.gradient(y, x)  # 2*x
dz_dx, dy_dx

(<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
 array([[ 0.6538882],
        [-3.392449 ],
        [ 1.3092967],
        [ 2.1058688]], dtype=float32)>,
 <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
 array([[ 1.0935647],
        [-1.8931329],
        [ 1.3783389],
        [ 1.6149303]], dtype=float32)>)

In [76]:
2*x

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 1.0935647],
       [-1.8931329],
       [ 1.3783389],
       [ 1.6149303]], dtype=float32)>

In [79]:
4 * tf.pow(x, 3)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 0.6538882],
       [-3.3924491],
       [ 1.3092967],
       [ 2.1058688]], dtype=float32)>